### ISSUE TITLE
Reset password link issue on chrome

### ISSUE THREAD

**Issue by marianthi-design** [nhsengland/futurenhs#150] opened 2022-05-11 14:01 UTC
When clicking on "forgot password" using Chrome, the reset password email doesn't come through. 2 users experienced this issue (Munsoor and Marianthi).

**Comment by Alex-Grubba-CDS** [comment] 2022-05-13 13:40
Question from @ReallySmall is this just on Chrome or any browser?

**Comment by marianthi-design** [comment] 2022-05-13 16:19
Just on Chrome.

**Comment by Matt-Beldon-CDS** [comment] 2022-05-27 10:56
Unable to reproduce this on chrome version 101.0.4951.67. 
From the users perspective does it appear like the email should have been sent or does it error?

**Comment by marianthi-design** [comment] 2022-05-27 12:00
It seems to be working now, thanks.

**Comment by Alex-Grubba-CDS** [comment] 2022-05-27 13:52
Output from Bug Triage session: 

If this is working @marianthi-design please can you close this issue.

**Comment by simplybenuk** [comment] 2022-06-13 10:09
Closing as no longer an issue

**Closed by simplybenuk** 2022-06-13 10:09 UTC
Labels: bug
